services:
  - type: web
    name: askdoc-agent
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y chromium chromium-driver
      pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
